name: test-ghcr-12345

on:
  workflow_dispatch:

jobs:
  test-ghcr-12345:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3
      - name: docker login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build && docker push
        uses: docker/build-push-action@v5
        with:
          context: inner/dir
          push: true
          tags: ghcr.io/${{ github.repository }}:inner
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
